### ISSUE TITLE
Hero image

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#134]
Cycle images in slideshow.

Load unique image each visit.

**Comment by joelworsham** [comment]
@banksashleym 

Could you take a look at the staging site and let me know what you think about the new hero image system? You'll probably want to do a hard refresh after loading the page once, just to ensure everything new is loaded.

**Comment by banksashleym** [comment]
Good morning!
Sorry, I'm not sure if I was clear enough in the previous e-mail...we are kind of switching gears and instead of the three stories rotating we would now like to feature just one story/message with a bank of about 10-15 images or so that would fade in/out of the background?

So to be more specific - dotty wanted to have the homepage hero message read "total commitment to student success" (and this one message would change about every two weeks or so) and then the learn more button would then link to a general marketing page where we would explain what total commitment to student success is...we would focus these hero image messages around broader topics like admissions and financial aid versus specific programs...So the message would remain the same (so the "total commitment to student success message would be out there for about two weeks), but then a bank of images would fade in/out behind that one message so that we have variety...sorry if the earlier e-mail didn't make sense...

Let me know if you have any questions!

**Comment by joelworsham** [comment]
Ah okay, sorry about the confusion. I'll get that setup.

**Comment by joelworsham** [comment]
All set. You still choose which Spotlight is used on the home page by making it featured, but now only one will be used, and it will be the most recently created. So just make sure you keep one featured at all times, and "un-feature" spotlights not currently in use.

Now each Spotlight accepts multiple images instead of one per Spotlight.

**Comment by banksashleym** [comment]
Awesome, this is great!!
Just one more thing and I will leave you alone :) Could we have the images fade in/out instead of sliding across? and could we also remove the burgundy slider at the bottom of the image that shows the progress until the next image shows up?

Thanks!

**Comment by joelworsham** [comment]
I can have them fade in/out, no problem. I would advise keeping the progress bar though. If it is important to have multiple images, then it is important for people to know there are multiple images to be seen, otherwise people will scroll past and not give it any thought. The progress bar informs users of a change that is going to happen and encourages them to stick around.

Might I ask for what reason you do not want this progress bar? Perhaps we can figure out an alternative indicator of more images coming?

Yes I can add the sidebar settings back to spotlights.

**Comment by banksashleym** [comment]
Awesome, thanks!
I don't have a problem with an indicator of more images...maybe we could do a series of dots or an unobtrusive arrow on either side of the picture so visitors could scroll through the images? My eye was immediately drawn to that progress bar since it was the only thing on the page that was moving, and it seemed a little distracting :)

**Comment by joelworsham** [comment]
Sure, fair point. I'll do some dots and see how that looks.

**Comment by banksashleym** [comment]
I like this a lot, thanks! The last thing I see is if the pics could just fade in/out this should be good to go! I love it. Once that's done I will send to Dotty and get her feedback, I'm sure she will think this is great as well.

Thanks!

**Comment by joelworsham** [comment]
Ah yes yes right. Sorry about that.

**Comment by banksashleym** [comment]
This is perfect! Could I have the ability to update the sidebar configuration? Then we should be set to go! I am going to get the spotlight story set and upload the images. Should I let you know when that has happened so we can move this over to the live side?

Thanks!

**Comment by joelworsham** [comment]
Well, once all of these issues are wrapped up, I'll do one large push to live with a new version.

**Comment by banksashleym** [comment]
Awesome, this is perfect! If I could just have you do one more thing and I will leave you alone for today :) Could we also take out the date that is below the header on the spotlight page? Once that is complete this is ready to be pushed over to the live side!

I just want to make sure that only the spotlight portion is going to be pushed over, correct? Just making sure that all of the changes we have made to the live side aren't going to be over-written?
