### ISSUE TITLE
Hero image link should include all public CPTs

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#41]

**Comment by banksashleym** [comment]
Kind of a side note on this issue...could we also integrate the news/events section as well? I just had a conversation with Marilynn, and we think there might be situations where there will be some overlap between news and events. The majority of our events will be quick down and dirty name/date/time information. However, there are some instances where we would like an event to have a little more weight and exposure. For instance, I have built an event "Martin Luther King Annual" celebration in the events plugin and included a nice long paragraph and image. This is a type of event that we would also like to feature in the news section as well.

Since it is an event above all, I would like the bulk of the content to remain in the events section, but is there a way we could still have this be an event, yet show up in the news section as well?

**Comment by joelworsham** [comment]
Hmmmmmm. The event does support showing content in the same way that featured news does. What about making an event "featured"? So that there is some sort of differentiation between a featured event and the others. Perhaps it could even get some sort of very short excerpt and image on the home page.

I'd like to avoid placing events in the featured news section though if possible. It would even be fine to create a featured news article in conjunction with the event, and leave the event page itself fairly empty. You can crosslink manually between them, so the user can see the featured news story about the event, read about it, and then see it on the calendar.

Thoughts?

**Comment by banksashleym** [comment]
Good deal, I like the idea of creating a featured news article in conjunction with an event and crosslink them, so that the event still shows up on the calendar. 

Thanks!
