### ISSUE TITLE
Primary Menu drop down

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#51]
I feel really dumb! Can you tell me how to add/edit content in the drop down menus for the primary menu (academics, cost & financial aid, etc...) the academics one is working when I hover over it and is pulling the child pages, but the other tabs are not. I have looked high and low on the dashboard and just can't figure it out! I went to appearance > menus > primary menu and see where all of the links are, and even set the cost & financial aid to the parent page, but it's still not pulling anything??

Thanks for your help!

**Comment by joelworsham** [comment]
No worries! I'm looking at it and am a bit confused myself. let me look into this.

**Comment by joelworsham** [comment]
Ah yes. The way I built this requires that there is a "description" for the menu item in order to show the megamenu dropdown.

I forgot to mention to you that you will need to (when on the nav menus page in WordPress) click "Screen Options" at the top of the page, and then check "Description" in order to edit the menu item descriptions. Once you've checked this, click the little arrow on a menu item to expand it, and now there is a "description" field. Enter the description there (this is that text block that shows up in the dropdown).

Also, in that description, you can add a link to the parent page (Like "Academics Home"), by putting the link text in double curly braces. So like this: `{{Academics Home}}`.

**Comment by banksashleym** [comment]
Good deal, thanks!

I am populating this area and would like to have the ability to control the links that show up in this menu as well if I could...A good example is the "Locations" tab. Each of our 5 campuses is its own "site section", but in order to have those campuses show up in the Locations drop down I need to make each campus have the parent page of a "Locations" page, but when I do that each of the campuses loses the ability to be a site section because it is now a child page...

Also, for Entertainment and Events, we have the Potter Center Season, Michigan Shakespeare Festival, and Requesting a Room Reservation. I would only like those links to show up in the drop down, as opposed to additional Potter Center Season information (like buying tickets and theater information)

**Comment by joelworsham** [comment]
For the time being, I think I'm going to make these megamenus a manual process. So you'll drag menu items as children in the menus screen just like other menus. I'll close this issue once I've completed that.
