### ISSUE TITLE
Tabs extending beyond main content area

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#58]
I added in some tabs in the Marketing section. When I click on the "We are Jackson College" tab the content extends beyond the main content area. I thought that it might have something to do with bringing in the formatting from our website now, but I looked at the text code and it's just a table without any additional formatting.

Thanks!

http://jacksoncollege.staging.wpengine.com/marketing-communications/publications/?preview_id=1563&preview_nonce=4a61770511&preview=true

**Comment by joelworsham** [comment]
Tables can be very finicky indeed... I think that a root cause of this though is that tables ideally should only be used for data, not so much layouts. Although, I know I did not originally give you layout tools for the content.

Albeit messy (I don't love using shortcodes for layout), I've added a couple new shortcodes for you to be able to use. You can now use `[row]` and `[column]`. The way it works, is you wrap your content in columns and you wrap your columns in rows. Example:

```
[row]
[column sizes="small-12 medium-6"]
Left on desktop and top on mobile
[/column]
[column sizes="small-12 medium-6"]
Right on desktop and bottom on mobile
[/column]
[/row]
```

Basically, these shortcodes simply give you direct access to the Foundation Grid, which is what the theme layout is built on. You can read up on it here http://foundation.zurb.com/grid.html. But the basics it that it's a 12 column grid, and you can have columns that take up a portion of that grid. So in this example, 6 is half, so you have 2 equal sized columns, each taking up half of the available space. The small and medium are for media query breakpoints. So, most columns are built off `small-12` so they become full width on small screens. You have available `small`, `medium`, `large`, and then some more that are very rarely used `xlarge` and  `xxlarge`.

See how this works out for you. As far as the HTML of the site goes, it is the correct way, the admin tools, as of now, are simply not the most user-friendly.

**Comment by banksashleym** [comment]
AWESOME!!! This is perfect :) lol, adding the content a table was my workaround so I could quickly insert the content, I believe this will work so much better.

Thanks!!

**Comment by joelworsham** [comment]
No problem! The only reason I consider it "messy" is because there's a lot of room for error with shortcodes like this. You have to be careful not to miss a quote, or a bracket, or forget to close a block (all of which is super easy to do, and I've done many times!).

But, it is definitely better than using HTML in the editor :P

Feel free to re-open this if you have any issues with it.

**Comment by banksashleym** [comment]
Sorry, I don't think I'm doing this right! When i copy the above shortcode, do I then just remove which size I don't want? 
on this sample page (http://jacksoncollege.staging.wpengine.com/sample-rowscolumns-page/?preview_id=7101&preview_nonce=13783f0821&preview=true):

the top is the code copied directly from what you have above with the two sizes, and the bottom is this code (where I have removed the "small-12" part:
[row]
[column sizes="medium-6"]
Left on desktop and top on mobile
[/column]
[column sizes="medium-6"]
Right on desktop and bottom on mobile
[/column]
[/row]

**Comment by joelworsham** [comment]
Right, so the issue here is that when you copied and pasted my code from here, it copied the `<pre>` and `<code>` tags with it. If you ever copy and paste from anything that's not WordPress, it's best to first  enable "Paste as Text", which is the little "T" button in the TinyMCE toolbar (you have to toggle the toolbar open if you haven't already)

**Comment by banksashleym** [comment]
Well check that out :) Cool, working now!

Thanks!

**Comment by joelworsham** [comment]
:+1:
