### ISSUE TITLE
Pop up/Welcome messages

### ISSUE THREAD

**Issue by banksashleym** [JacksonCollege/Primary-Theme#63]
This was another area on my list that I wanted to touch base on.

Right now we have two pop up messages (basically just a browser window that pops up when a student/employee logs into the computer) at www.jccmi.edu/welcome and www.jccmi.edu/welcome/students.asp.

Just getting this on the list to discuss as well!

**Comment by joelworsham** [comment]
Feel free to give these a try. They are found in "Alerts".

Hopefully it's mostly self-explanatory, but feel free to ask questions about it here.

**Comment by banksashleym** [comment]
Awesome, this looks good for an emergency alert!

I think we brought this up at one of our earlier meetings a long time ago, and I haven't thought about it until now sorry...but we also have our daily pop up messages (www.jccmi.edu/welcome will pop up when an employee logs in to their computer and www.jccmi.edu/welcome/students.asp is what shows up when a student logs into the computer.) it's basically a browser that will pop up when a user logs in and lets employees/students what is going on that day. This feature is independent of the website (the page is on our site, but a visitor doesn't necessarily have to go to the website to view this pop up - it's something our IT department has set up to pop up when you first log in). Could we just set up a blank page with minimal formatting (not tied to the theme) where we could interchange out the daily pop up and then supply that URL to our IT department so that they are able to make that specific page pop up?

**Comment by joelworsham** [comment]
Right, so there's a few courses of action we can take:

1) I can make it so the alerts are accessible via a query parameter in the URL. Example: `jccmi.edu?alert=84` (84 is an arbitrary example of an alert ID). This way, you give your IT department the URL to show specific alerts. This URL would take the user to the homepage and then show the pop up alert. This would be really nice because it would stylistically be very pleasing and they would already be on the website if they needed to go there anyways. This is my recommended course of action.
2) I can make a minimalistic page template to use that you can use for these "pop up" pages, and enter the content as desired. This would exist entirely outside of the alerts system. I don't love this idea because they would be getting a very ugly (aesthetically speaking) experience as well as the page becomes useless aside from the message itself (which a lot of people probably ignore). They have to navigate to the website separately. Also, it would not feel as "inclusive" with the website, which I personally see as a downside.

**Comment by joelworsham** [comment]
Also, more to point 1.

I can allow that URL to be pretty, if absolutely desired. So you could keep jccmi.edu/welcome, but it would still load the homepage with the alert popup

**Comment by banksashleym** [comment]
Good deal, let me talk this over with everyone...so if we went with the first way, would we have to supply IT with the URL every day with which alert we would like them to use? I believe it's set up now where Marilynn can populate an asp page with the whole month's worth of pop ups, and when the date changes it automatically changes on that /welcome page...I wouldn't put too much effort into this, it has been something we've been meaning to talk about whether or not to keep them or not. I will suggest the first way. And the alert pop up would only show up when logged into the computer for the first time? I wouldn't want it to pop up for everyone and every time someone goes to the web site.

**Comment by joelworsham** [comment]
Some more clarification on point 1:

- The URL would be the same always. `jccmi.edu/welcome` (and if you wanted a different URL for students, then also `jccmi.edu/welcome-students` or `jccmi.edu/welcome/students`, really whatever you desire).
- It would be possible to create a backlog of alerts and schedule them for publishing so it could be automatic.
- I think what I would do is give you either a taxonomy or simply a couple radio boxes on each alert so you can choose "Faculty" or "Students". This would determine what each respective URL showed. It would probably show the most recent in date (this would also aid in scheduled publishing)

**Comment by banksashleym** [comment]
Good morning Joel,
I just received an email from our IT department regarding these pop ups regarding the two urls, one for the employee pop up and one for students (see below). I don't necessarily think these have to be pretty urls, but if you want to keep the jccmi.edu/welcome for employees and jccmi.edu/welcome-students that would work! Also, I just wanted to clarify that when we do these alerts they are only going to show up for those two specific urls, and not on the main page when a visitor goes to the website. Thanks!

Hi Ashley,
What is the URL for the new daily pop-up messages site? I want to make sure that I get this to Michael so he can apply it to all campus computers on 2/2/16.

**Comment by joelworsham** [comment]
Sounds perfect. Yes, these specific alerts will ONLY show up when going to those URL's, and when those alerts show, they will be a popup over the homepage.

I'll put this together and you can take a look.

**Comment by banksashleym** [comment]
Sounds great! I like how they are set up so that when an employee/student does click off of the alert they will be on the home page :) 

THANKS!!

**Comment by joelworsham** [comment]
Alright, so after some testing I've developed a new system that's a bit different than described above. Let me know how it works for you.

When you create an alert, you can copy the public URL of the alert (viewable under the alert title and also through the buttons that say "view alert"). When you view these alerts you will be taken to the homepage and the alert will show (the URL will contain a query parameter for the url to show).

So this way you can either hand over to IT the url that looks like `http://www.jccmi.edu?jc-alert-id=###` or you can give them `http://www.jccmi.edu/jc-alert/alert-name`. Both will work.

If it's critical to you to have the URL show `http://www.jccmi.edu/welcome/students`, for instance, we can continue iterating on this as it will be a bit more complex.

**Comment by banksashleym** [comment]
Awesome! So if I gave IT this URL "http://www.jccmi.edu?jc-alert-id=###" that would be used for both the student and employee URL? And I would be able to differentiate in Wordpress which alert I want to designate as a student or employee alert?

And if I schedule out the pop ups in advance (one for each date) they would automatically switch out based upon the date I have scheduled?

Sorry for all of the questions :)

**Comment by joelworsham** [comment]
The `###` was only a placeholder for the actual alert ID. You'll need to create the alerts now, view them both, and copy/paste the URL for each, keeping track of which is which.

Then, in the future, you can simply edit those alerts to update them with the proper information.

For scheduling, this would not currently work with this system. Perhaps we can figure out a way to do that in the future though!

**Comment by banksashleym** [comment]
Ok, I think we are going to hold off on the pop ups until we can get them to be scheduled if that's ok? We are just concerned that the pop ups over the weekend and on Monday morning would not change since we won't be here to update them. Could we re-direct www.jccmi.edu/welcome (this is the url for employees) and www.jccmi.edu/welcome/students.asp (the pop up for students) to just pop up with the home page for the time being so that when a student or employee logs in it will pop up with the new website? 

Sorry for the last minute change!

**Comment by joelworsham** [comment]
We can do that for now. I didn't actually realize the current system was automated. I'll make sure to get that working soon.

**Comment by joelworsham** [comment]
@banksashleym 

Alrighty, I have adjusted the system to work properly now.

Basically, when making an alert, there are 3 radio fields in the "Visibility" meta box under "Use for Welcome Message". It defaults to "none" and, if the alert is not used for a welcome message, then you can ignore it and leave it is. If you want to use it as the welcome message viewable at the URI `/welcome/`, then select "Staff". If you want to use it as the welcome message viewable at the URI `/welcome/students/`, then select "Students".  If you have alerts that exist that are set as Welcome Messages, then visiting the above `URI`'s will redirect to the homepage and show the alert.

This system will display the **newest** alert (by publish date) only. So if you have 2 alerts set as the "Staff" Welcome Message and you visit `/welcome/`, only the newest alert will show. This will allow you to schedule alerts out. So that you may have 1 alert setup for this and published, and a second alert setup for this but scheduled. Once it's published, it will become the new Welcome Message and you can delete the previous alert, remove the "Use for Welcome Message" radio, or simply leave it as be. If you need to revert to a previously used alert for a Welcome Message, either re-schedule it for a future publish date, or manually adjust the publish date for switching immediately.

Let me know if you have any questions and if this works for you guys.

**Comment by banksashleym** [comment]
Sorry I haven't had a chance to test these until today! This is perfect :) I tested on the staging side and everything looks good! Will this new functionality have to be moved to the live side of the site? I did notice that when i create a new alert on the live side the student/staff radio buttons are not showing up.

Thanks for all of your work on this!

**Comment by joelworsham** [comment]
Glad to hear! I'll push this to live right away.
