### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by joelworsham** [JacksonCollege/Primary-Theme#83]
Get em done

**Comment by banksashleym** [comment]
Just wanted to make you aware of this - a lady from our IT department was on the staging site and noticed some things going on with re-directs not going where they are supposed to? Either that or she would put in a word at the end of the http://jacksoncollege.staging.wpengine.com/ and it almost do a search and find relevant information to direct to?

For example she typed in http://jacksoncollege.staging.wpengine.com/it and it re-directed to the IT Liaisons page
Or
http://jacksoncollege.staging.wpengine.com/president and it directs to a news item on our president.

Also, I am going through each page and checking links, and on the accounting page, the schedule tab links to our e-services, when it is set up in the side nave menu to link to the Accounting Schedule page. There is a redirect set up on our current site for /schedule that links to e-services, and I'm wondering if it's being applied everywhere throughout the site where it sees the word "schedule"?

http://jacksoncollege.staging.wpengine.com/program/accounting/

Not sure if this is only because it's on the staging, but if we could have it so that pages are only re-directed if a re-direct is set that would be great!

**Comment by joelworsham** [comment]
For the first couple redirect questions, this is WordPress. When you hit a page that doesn't exist on a WordPress site, WP does its best to keep you from hitting a 404 page. So sometimes you end up at a page with part of the slug containing where you were trying to go, rather than just hitting a 404 page.

For the e-services question, this is fixed now that the redirects don't apply to staging, but it will apply to live. I copied over the redirects list from the other day into WP Engine. These are viewable [here](https://my.wpengine.com/installs/jacksoncollege/redirect_rules).

If you feel that any of them should not exist, either let me know, or feel free to simply delete them.

**Comment by banksashleym** [comment]
Good deal, thanks for the clarification!
